# Generated by Django 4.2.3 on 2023-07-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Enter your Facebook URL')),
                ('linkedin', models.URLField(blank=True, help_text='Enter your LinkedIn URL')),
                ('twitter', models.URLField(blank=True, help_text='Enter your Twitter URL')),
                ('mastodon', models.URLField(blank=True, help_text='Enter your Mastodon URL')),
                ('youtube', models.URLField(blank=True, help_text='Enter your YouTube URL')),
                ('instagram', models.URLField(blank=True, help_text='Enter your Instagram URL')),
                ('snapchat', models.URLField(blank=True, help_text='Enter your Snapchat URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_button_text', models.CharField(blank=True, default='Form', help_text='Enter the text that will appear on the contact button', max_length=32, null=True)),
                ('call_button_text', models.CharField(blank=True, default='Call', help_text='Enter the text that will appear on the call button', max_length=32, null=True)),
                ('call_button_number', models.CharField(blank=True, default=None, help_text='Enter the number to call', max_length=32, null=True)),
                ('book_button_text', models.CharField(blank=True, help_text='Enter the text for make booking', max_length=32, null=True)),
                ('book_button_link', models.URLField(blank=True, default=None, help_text='Enter the URL to make a booking', max_length=64, null=True)),
                ('contact_button_page', models.ForeignKey(blank=True, help_text='Select the contact form page to link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
